# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fluent-plugin-flume-ng"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["DEMING ZHU"]
  s.date = "2015-06-10"
  s.description = "Fluentd Plugin For New Generation Flume"
  s.email = "deming.zhu@linecorp.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    "Rakefile",
    "VERSION",
    "fluent-plugin-flume-ng.gemspec",
    "lib/fluent-plugin-flume-ng.rb",
    "lib/fluent/plugin/in_flume_ng.rb",
    "lib/fluent/plugin/thrift/flume.thrift",
    "lib/fluent/plugin/thrift/flume_constants.rb",
    "lib/fluent/plugin/thrift/flume_types.rb",
    "lib/fluent/plugin/thrift/thrift_source_protocol.rb"
  ]
  s.homepage = "http://github.com/Deming Zhu/fluent-plugin-flume-ng"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Fluentd Plugin For New Generation Flume"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_runtime_dependency(%q<fluentd>, ["~> 0.10.16"])
      s.add_runtime_dependency(%q<thrift>, ["~> 0.8.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<fluentd>, ["~> 0.10.16"])
      s.add_dependency(%q<thrift>, ["~> 0.8.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<fluentd>, ["~> 0.10.16"])
    s.add_dependency(%q<thrift>, ["~> 0.8.0"])
  end
end

